export const AUTHORIZE_SIGNUP = 'AUTHORIZE_SIGNUP';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REQUEST_ROUTE = 'REQUEST_ROUTE';
export const CLEAR_REQUEST_ROUTE = 'CLEAR_REQUEST_ROUTE';
